### ISSUE TITLE
MobileIron (Master Issue)

### ISSUE THREAD

**Issue by mocasorla** [n00neimp0rtant/xCon-Issues#26]
Not sure if this is something in the radar for you, but it seems more and more companies are implementing this MobileIron client for email on mobile devices such as iPads and iPhones, our company is and it is a Hughe pain in the rear because now is detecting JB devices personal and corporate issued devices, at any rate if there's anything you can do it will be greatly appreciated, the app is available in the U. S. app store for both iPad and iPhone.

Thanks again,

**Comment by shapez0r** [comment]
Hi @Lunat1k 
Latest MobileIron https://itunes.apple.com/us/app/mobileiron-mobile-work-client/id320659794?mt=8
still detects jailbreak =(

**Comment by mocasorla** [comment]
Yes, they actually updated it earlier this year, unfortunately I do not
have a copy.

On Wed, Jul 8, 2015 at 4:45 AM shapez0r <notifications@github.com> wrote:

> Hi @Lunat1k <https://github.com/Lunat1k>
> Latest MobileIron
> https://itunes.apple.com/us/app/mobileiron-mobile-work-client/id320659794?mt=8
> still detects jailbreak =(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/n00neimp0rtant/xCon-Issues/issues/26#issuecomment-119548045>
> .
>
-- 

Best Regards,


Mo Casorla

mocasorla@gmail.com
520.631.4897 -

**Comment by shapez0r** [comment]
so.. you need an .ipa? or you are not going to dig into mobileiron anymore?

**Comment by dt56** [comment]
Also very interested in a fix for this.  My company has, up until now, let it go for MobileIron.  Now they say they will block JB.  Any help appreciated!!!

**Comment by slashhesham** [comment]
does anyone have the .ipa for 4.5.30 ??? I've been searching for days and I can't find it anywhere.
