### ISSUE TITLE
Ziggo TV

### ISSUE THREAD

**Issue by Lastminuteguy** [n00neimp0rtant/xCon-Issues#278]
First of all, my thanks for all the work you've done. I'm a big fan.

Remember #75 ? They've found a way to bypass xcon. 

Could you take a peek in the new version? I've added a cracked version in the link below. Would you be so kind to erase the link after you've downloaded the cracked version?

Thanks.
https://www.dropbox.com/s/9jungcwosd4jer9/Ziggo%20TV-v59.ipa

**Comment by DL-Zeratul** [comment]
Why are you opening a new issue if there is already #75?

**Comment by Lastminuteguy** [comment]
Isn't your comment a bit late and irrelevant by now?

**Comment by Lunat1k** [comment]
Duplicate of #75
