### ISSUE TITLE
Barclays Mobile Banking on iOS 7

### ISSUE THREAD

**Issue by viperzltd** [n00neimp0rtant/xCon-Issues#341]
It doesn't look like anyone has opened an issue for this app. I've search the issues list but sorry is this does become a dupe of another issue. Neither apps work on their respective devices

iPhone Version 1.7 (Updated but link still valid):
https://itunes.apple.com/gb/app/barclays-mobile-banking/id536248734?mt=8

iPad Version 1.4:
https://itunes.apple.com/gb/app/barclays-mobile-banking-for/id589557591?mt=8

I'm currently using iPhone 5 on 7.0.4, and iPad 3 on 7.0.4 if that provides any support
Both devices crash roughly 30-60 seconds after opening the app but also sometimes instantly crash.
I've tested both apps with xCon v39 b7

**Comment by Lunat1k** [comment]
Closing - Duplicate of #61
