### ISSUE TITLE
Ziggo app detecting jb

### ISSUE THREAD

**Issue by Emptyless** [n00neimp0rtant/xCon-Issues#457]
Dutch ziggo app still detecting jailbreak in latest xcon beta

**Comment by dnogwat** [comment]
Indeed! The ziggo tv app has been updated some days ago. Now xcon doesn't work anymore, please release an update!

**Comment by DL-Zeratul** [comment]
Why are you opening a new issue? There is already #75.

**Comment by Lunat1k** [comment]
Duplicate of #75
