### ISSUE TITLE
SUBWAY® App 

### ISSUE THREAD

**Issue by bg49130** [n00neimp0rtant/xCon-Issues#458]
SUBWAY® App by SUBWAY Restaurants
https://appsto.re/us/xCOW1.i

The app seems to not be covered by Xcon so far.
Your assistance to patch this jailbreak detection would be greatly appreciated.

![image](https://cloud.githubusercontent.com/assets/10878438/6075681/170b6100-ad9d-11e4-8b4b-641371cf9e06.jpg)
![image](https://cloud.githubusercontent.com/assets/10878438/6075683/17222d90-ad9d-11e4-9960-ad9df25c2c3c.jpg)

**Comment by Lunat1k** [comment]
Use the Latest Beta V40 Beta 2 and It'll work. I actually use it quite often
