### ISSUE TITLE
Read-only SQLite3 databases with xCon v40b1

### ISSUE THREAD

**Issue by rctgamer3** [n00neimp0rtant/xCon-Issues#459]
Google Maps (and a handful of other apps) crash if they can't write to their storage in their respective Library/ApplicationSupport folder because the archives are read-only (and then obviously can't be changed by the app) on launch.
The files don't have write permissions when viewed in iFile, confirming that they are in fact read-only.

If xCon is (temporarily) removed or disabled, and the files/and or permissions of the database file are reset or the database deleted, the apps launch just fine.

**Comment by RiotNrrrd** [comment]
I'm not 100% sure, but I think this might be the same problem with an issue I was seeing.  I installed Citymapper on my iPad (where I use xCon for DirecTV for iPad access) and it was not able to download files for 'new' cities that had been added.  I looked in the syslog file and saw a reference to a "scribe.sqlite" database file error.  This smells like the same problem.

Citymapper worked fine on my iPhones (where I use a Flex 2 tweak to enable the DirecTV app and don't have xCon installed) and was able to download these city files, so I'm sure it's xCon that is either blocking the download sites by mistake, or it's this issue with the database files becoming read-only.

xCon 40 appears to be a bit of a mess :(

**Comment by Lunat1k** [comment]
Try Beta3. I had a fix to one of the System APIs

**Comment by Lunat1k** [comment]
Also I found you may need to uninstall and reinstall the app to fix the permissions. IE I had a problem with Target and Groupon.

**Comment by Lunat1k** [comment]
Beta5 should finally fix this issue
