### ISSUE TITLE
xcon breaks Dropbox (files can't be opened). 

### ISSUE THREAD

**Issue by huphup** [n00neimp0rtant/xCon-Issues#477]
Hi, since I have installed xcon most files in dropbox can't be previewed or opened in other apps. As soon as I uninstall xcon dropbox works just fine. I really hope you can fix this. Thanks a lot!

**Comment by DirkSwizzler** [comment]
I was just about to report this. Confirmed that downloads do not work. 

I mostly care about downloading and opening in other apps. But previewing txt files illustrates the behavior in a simpler test case.

This is the test I performed this morning:
1. Without xCon installed, I can preview the test txt file.
2. Installed xCon 40 beta 2. Can't preview the test txt file.
3. Uninstalled xCon, resprung. Can preview the test txt file again.

Verified this behavior twice.

On a somewhat related note. Beta 2 totally fixed the "Mail" app behavior I reported a few months ago. And from the notes the only change is not injecting into stock apps (such as "Mail").

Maybe the quickest fix here is to enumerate all apps and selectively enable xCon for only a few?

I really only need it for the TiVo app.

**Comment by icebox766** [comment]
Iphone 5 xcon 40b2. I can preview files without trouble in dropbox. 
Tried it on an rtf file and a txt, both worked.  

If you only need xcon for one app, get iCleaner pro, which lets you disable cydia apps without uninstalling.

**Comment by DirkSwizzler** [comment]
Oops, forgot to mention other test variables:

iPhone 6, iOS 8.1 (12B411)

**Comment by DirkSwizzler** [comment]
iCleaner pro is a worse solution than uninstall/reinstall. It requires respring both on enable and disable.

Installing and uninstalling xCon only requires respring on uninstall. Install works immediately.

**Comment by huphup** [comment]
I definitely can't open any PDF/Word or Excel file in Dropbox with the latest xcon and DB Version installed. This has also been confirmed here: https://github.com/n00neimp0rtant/xCon-Issues/issues/429 
Tested it with an iPad Mini 2 and an iPhone 6 both on iOS 8.1.2

**Comment by Lunat1k** [comment]
Try Beta3 I made a fix to the Open Call

**Comment by huphup** [comment]
Hi Lunat1k. I just installed Beta3 but the problem remains. Is there anything I can do to to help you finding the issue?

**Comment by DirkSwizzler** [comment]
Tried Beta3 on iPhone 6, iOS 8.1 (12B411).

No change in Dropbox behavior. Still can't preview files unless they were downloaded prior to installing xCon

**Comment by Lunat1k** [comment]
Beta5 should work now

**Comment by huphup** [comment]
I can confirm that the issue is fixed now! Thanks a lot as it was very inconvenient opening all dropbox files in ifile and the db app itself.

**Comment by DirkSwizzler** [comment]
Yep, that did it!

Thank you, thank you, thank you!

**Comment by Lunat1k** [comment]
No Prob. I'll close this issue out.
