### ISSUE TITLE
>>Paper 53<< app problems with xCon

### ISSUE THREAD

**Issue by annrein** [n00neimp0rtant/xCon-Issues#479]
I wonder whether there is any possibility to suspend Paper 53 from xCon. xCon works fine for me but I can't use my painting app >>Paper 53<< with xCon enabled. The covers of the books are gone.
with xCon
![image1](https://cloud.githubusercontent.com/assets/11346556/6522043/a613d38e-c3df-11e4-86dc-94bb9f3d301f.PNG)
without xCon
![image2](https://cloud.githubusercontent.com/assets/11346556/6522048/bcd3b918-c3df-11e4-9ff6-a91224955518.PNG)

**Comment by Lunat1k** [comment]
Latest beta should fix the issue. It was a problem with one of the Apis I hook into.

**Comment by annrein** [comment]
Yes, works fine now. Thank you!
