### ISSUE TITLE
xcon 40 beta2 crashes Spotify

### ISSUE THREAD

**Issue by spitfire** [n00neimp0rtant/xCon-Issues#481]
After I've installed xcon, Spotify started to request login information everytime app started (but worked after logging in) After I've reinstalled Spotify (still having xcon installed - to see if that solves the problem)  it was immediately crashing on startup. Removing xcon fixed both issues.

**Comment by Lunat1k** [comment]
Try Beta3. I had a fix to one of the System APIs

**Comment by Lunat1k** [comment]
Beta 5 should fix you up.

**Comment by spitfire** [comment]
Thanks! Or maybe I should wait for beta 7? :)

**Comment by Lunat1k** [comment]
Naw I think I finally got it working right. The open API is kind of tricky

**Comment by spitfire** [comment]
It seems to be working. Thanks for your help!
