### ISSUE TITLE
xcon Breaks Mailbox by Dropbox

### ISSUE THREAD

**Issue by baudencm** [n00neimp0rtant/xCon-Issues#484]
Love the app for TWC. However it broke Mailbox by Dropbox. Maybe similar to the Dropbox issue? Keep up the great work and thank you!

**Comment by baudencm** [comment]
(Sorry, ios 8.1.2 on iPhone 5s with Mailbox version 2.4.1)

**Comment by Lunat1k** [comment]
Try Beta3. I had a fix to one of the System APIs

**Comment by baudencm** [comment]
Thanks for the update! Since I did not see beta3 on Cydia, I managed to install the deb file using iFile. It shows up in Cydia installed apps now so I think I did it correctly. 

Mailbox now works with beta3. TWC still works. Great work and thank you!

**Comment by Lunat1k** [comment]
Beta 5 fixes some other issues. I would suggest upgrading when you get a chance.

**Comment by baudencm** [comment]
Got it! Everything ok so far. I appreciate the update...
