### ISSUE TITLE
Snapchat 9.9.0

### ISSUE THREAD

**Issue by learntofly83** [n00neimp0rtant/xCon-Issues#493]
Xcon 40 beta 5 is crashing (well not allowing login) on the latest snapchat 9.9.0. this happens regardless of whether snapchat tweaks such as phantom are installed. Does not produce a crashlog though?

**Comment by pcgamers123** [comment]
Got the same problem, had to uninstall xCon cuz of it.

**Comment by moleculo77** [comment]
Same issue here, had to downgrade to previous version and everything is working fine.

**Comment by learntofly83** [comment]
This is no longer and issue, fixed at some point between issue opening and the v40b8 release (with "ldid -S /Library/MobileSubstrate/DynamicLibraries/xCon.dylib" command)
