### ISSUE TITLE
Directv iPad app 4.0.2

### ISSUE THREAD

**Issue by ussvoyager** [n00neimp0rtant/xCon-Issues#497]
Will con be updated for the directv iPad app version 4.0.2?  I could not find anything listed in the current issues for this version.  I tried the current version of xcon, but it didn't work. Also, i am using ios 8.3 jail broken.

**Comment by Lunat1k** [comment]
it won't work on 8.3 until taig fixes the mobilesubstrate issue. Otherwise the latest beta should work fine.

**Comment by ussvoyager** [comment]
Awesome, thanks for the reply
