### ISSUE TITLE
iOS 9.0.2 iPhone 5s safe mode

### ISSUE THREAD

**Issue by JetP1L0t** [n00neimp0rtant/xCon-Issues#536]
subj
installed 40b5
getting "Safe mode" after reboot or respring

**Comment by Lunat1k** [comment]
I'm waiting to upgrade before I support iOS 9. Some stuff I need is still not supported yet.

**Comment by Lunat1k** [comment]
Can you install this version and tell me if it's fixed. I'm still not on iOS 9 yet but I've talked with a few other developers. https://goo.gl/jFYBeX

**Comment by JetP1L0t** [comment]
Lunat1k, this one gives same - safe mode after respring or reboot.

JFYI: old version 38 or 39 doesnt cause safe mode & doesn't work.

**Comment by Lunat1k** [comment]
Try this version. I was compiling it wrong. https://goo.gl/rcGmgv

**Comment by JetP1L0t** [comment]
respring == safe mode
reboot == blue screen + safe mode

i cann't install "syslogd to /var/log/syslog"
```
S:pmstatus:syslogd:20:Preparing syslogd
dpkg: error processing /var/mobile/Library/Caches/com.saurik.Cydia/archives/syslogd_1.1.1_iphoneos-arm.deb (--unpack):
 subprocess extra-installation script returned error exit status 1
S:pmerror:/var/mobile/Library/Caches/com.saurik.Cydia/archives/syslogd_1.1.1_iphoneos-arm.deb:20:subprocess extra-installation script returned error exit status 1
Errors were encountered while processing:
 /var/mobile/Library/Caches/com.saurik.Cydia/archives/syslogd_1.1.1_iphoneos-arm.deb
/bin/cp: `/var/mobile/Library/Caches/com.saurik.Cydia/extended_states' and `/var/lib/apt/extended_states' are the same file
E:[Sub-process /usr/libexec/cydia/cydo returned an error code (1)]
2015-10-21 19:46:44.640 Cydia[825:6094] unexpected nil window in _UIApplicationHandleEventFromQueueEvent, _windowServerHitTestWindow: <UIWindow: 0x37b2f0; frame = (0 0; 320 568); userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x354530>; layer = <UIWindowLayer: 0x33a720>>
S:pmstatus:dpkg-exec:0:Running dpkg
```
syslog in itools app not working too & still cann't find out how to get some logs

**Comment by Lunat1k** [comment]
Install CrashReporter. This will give more information.

**Comment by JetP1L0t** [comment]
Installed CrashReporter, it shows nothing like everything is Ok.
![img_0016](https://cloud.githubusercontent.com/assets/5320214/10647001/c4c50780-783e-11e5-9616-d94e8c1e47e0.PNG)

maybe better to wait till 9.1 jb release?

**Comment by zallthat** [comment]
IPhone 6 Plus on iOS 9.0.2. Beta 8 (and beta 5) allow DirecTV app to bypass JB detection message, but app crashes while finishing the load phase.

**Comment by JetP1L0t** [comment]
Wow, re-updated my firmware to 9.1 then back to 9.0.2 and now _beta_8 not causing safe mode!
But still doesn't hide JB from needed app.

**Comment by imatechnerd** [comment]
I'm getting safe mode and instability issues (Safari crashing, "no cellular network" alerts, Phone issues) using Beta 8 on iPhone 6S, iOS 9.0.2. 

FYI, for DirecTV you need to turn off Minimal Hosts Blocker for it to load, then you can turn it back on. 

I really appreciate you guys working on this. How do I contribute?

**Comment by ghosthost33** [comment]
Using beta 8 on ios 9.0.2 iphone 6splus. Still in safe mode, but camera stopped working and facetime was a black screen.

**Comment by JetP1L0t** [comment]
ghosthost33, it has a conflict with one of:
Substrate Safe Mode 0.9.5000
Cydia Substrate 0.9.6011
PreferenceLoader 2.2.3-3

without this packages xcon doesn't cause any "visible" crash but it doesn't work too.

**Comment by ghosthost33** [comment]
Thank you JetP1L0t. Here is hoping for a stable version sooner than later!

**Comment by johnsoninnyc** [comment]
Lunat1k - seems this is close.  If I set the filter plist to a specific app the phone regains normal/stable function.  b8 (unlIke b7 and everything prior) is successfully loading into armv7 and armv6 apps now  (module/file open to xcon dylib shows using cocoatop).  But there is a problem with entitlements which sprays all over the syslog and crashes the app or makes v unstable at  best.  

Perhaps fixing this entitlements bit is all that's needed to at least have a properly loading, stable test version?

**Comment by Maestro64** [comment]
I can confirm I put beta8 on a iPad with 9.0.2 not problems running but still does not hide the jailbreak from programs like DTV.

Good luck finding a fix, appreciate all your past efforts keeping it a live.

**Comment by johnsoninnyc** [comment]
seems that 40b8 simply requires a trivial code signing step.   it is a simple one line command - I posted instructions just now under the 'xCon Good for Enterprise Issues ' thread here on GitHub.  

make sure to grab today's Cydia Substrate update, and  then follow those instructions to run 'ldid -S ' on the xCon dylib binary.   this seems to get ex-con loading into all apps , without a log full of security errors, crashes etc.   

happy testing. .

**Comment by ghosthost33** [comment]
It seems to be working here at my end...looking good so far!!

**Comment by johnsoninnyc** [comment]
great -- have you been able to confirm functionality on any apps yet?

**Comment by ghosthost33** [comment]
Biggest problem is finding something that won't work!!! Thank you so much!
Still going through them but this is solid so far!

**Comment by JetP1L0t** [comment]
Thanks, @johnsoninnyc !
This way works.
Confirmed to work with russian "Sberbank Online".

**Comment by fiatuno49** [comment]
Thanks, @johnsoninnyc !
Xcon 40~beta8 and your command line
"ldid -S /Library/MobileSubstrate/DynamicLibraries/xCon.dylib" 
Works well with Record Bank Mobile  ( ios 9.02 Iphone 6)

**Comment by filthyjason** [comment]
40~beta 8 is working for me. I'm testing on an iphone 6, 9.0.2. I ran the command line bit after and now Directv app works. I think that's the only app I had which does j/b detection and it was failing before I installed beta 8.
Thanks!

**Comment by johnsoninnyc** [comment]
sweet guys!!  we survive yet another ios update. .

and much thanks to Lunat!k for recompiling xCon, and eternal thanks to n00ne and saurik for making this all possible. 

happy days!

**Comment by zeeshaaan** [comment]
Hi I'm new to this I downloaded the deb file on to my phone. I then installed the file on ifile. The tweak does not seem to work still.:-(. I need idiot proof guide. The Uber app is still ant working

**Comment by johnsoninnyc** [comment]
follow instructions to run ldid -S , under the good for enterprise issues thread listed under this project (xCon) here on github.

that's as close to idiot proof as you can reasonably expect on a development-only site like GitHub..

**Comment by Maestro64** [comment]
Thanks, @johnsoninnyc 

I got it working on DTV it was a little touch and go there for a while things were not working, app kept crashing but it seems to have clear up now. The only issue not is PLEX will not run, it was working fine before I made all the changes listed here so there may be some sort of side effect.

**Comment by azroach** [comment]
@zeeshaaan

you need to root into your device and enter the following:

ldid -S /Library/MobileSubstrate/DynamicLibraries/xCon.dylib

**Comment by JetP1L0t** [comment]
somebody "built" v41 at jailbreakvideo.ru repo that works out-of-the-box, ticket solved

**Comment by azroach** [comment]
lol

**Comment by azroach** [comment]
cool thanks
