### ISSUE TITLE
Uber Driver Jailbreak Detection IOS 9.02 

### ISSUE THREAD

**Issue by Stuballz** [n00neimp0rtant/xCon-Issues#538]
Hello
Please upgrade version of Xcon for IOS 9.02, that works for Uber Driver Jailbreak Detection
Thank you

**Comment by zeeshaaan** [comment]
Does scones beta 8 work for this ?

**Comment by jthais** [comment]
Is there any way we can get this to work on IOS 9.1 and 9.3.3 please?

**Comment by zeeshaaan** [comment]
Download liblocation Xcon works fine with me 

Zee

**Comment by jthais** [comment]
Thank you for that I will try that! So download the tweak liblocation with xcon and I should be good?

**Comment by jthais** [comment]
It didn't work sir? :/ do you drive uber as well?

**Comment by zeeshaaan** [comment]
I do drive for uber which version of Xcon did u download it needs to be 41 version

Mines been working fine 

Zee

**Comment by jthais** [comment]
I tried all xcon versions in cydia I'm testing these out on my moms phone that's jailbroken on 9.1. Mine is on 8.4 using version version 40 beta 5 and it's working. I want to update but not till it's tested and working on my moms phone. Thanks for helping me. What iOS version are you on?

**Comment by Stuballz** [comment]
The only version of xcon that works for Uber on iOS 9.02 is Version 41 it is not authorized by the original author and can only be found on repos that usually carry pirated software

**Comment by zeeshaaan** [comment]
I'm using 9.3.3 I did the same on my Mrs phone first then when I was successful I did mine. 

Zee

**Comment by jthais** [comment]
Nice man I'm going to try the insanleyi repo with xcon 41 on 9.3.3 I'll let you know thanks

**Comment by jthais** [comment]
Yeah I'm using the insanelyi repo I'm going to give if a shot on xcon 41

**Comment by jthais** [comment]
Xcon 42 beta 1 just rolled out FYI

**Comment by jthais** [comment]
That one worked thank you!
