### ISSUE TITLE
xCon 41 don't work wit C More

### ISSUE THREAD

**Issue by Skevus** [n00neimp0rtant/xCon-Issues#544]
C More is a Streaming Service like Netflix or Hulu+. When Jailbroken and I start watching it just spins and spins forever without ever starting to play the movie, No messages or anything. Greatings....

Here is the IPA File if you can help out:

http://www.filedropper.com/cmore115

<a href=http://www.filedropper.com/cmore115><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file backup online</a></div>

**Comment by Lunat1k** [comment]
There is no V41. I wouldn't trust it since I never released that version. The last one I posted but forgot to put on the front page was V40 Beta 8. I use Netflix and Hulu all of the time so I would recommend using the offical beta version.
