### ISSUE TITLE
I don't trust the unofficial v41. When are you guys ready wit the new iOS 9 version?

### ISSUE THREAD

**Issue by piejanssens** [n00neimp0rtant/xCon-Issues#545]

**Comment by Lunat1k** [comment]
I wouldn't trust it either as I never released a v41. I'm still on 8.4 so I cannot even dev/test it until 9.3.1 is jailbroken.

**Comment by Maestro64** [comment]
okay that explains why no updates for a while. The question now, will there be a JB version of 9.x beyond 9.0.2 we have today.

**Comment by greelg** [comment]
Is there anyway to help you get a device on iOS 9? I'd really like to play Miitomo on my 9.1 device
