### ISSUE TITLE
Pokemon Go

### ISSUE THREAD

**Issue by hoseayeee** [n00neimp0rtant/xCon-Issues#576]
Jailbreak detection not working please fix

**Comment by nwpulele** [comment]
It works on my iPhone 6, iOS 8.1.1

**Comment by Iomega0318** [comment]
tsProtector 8+ will work with Pokemon Go, I'm on iOS 9.1, that's about the only app it seems to work with for the moment though haha.. You can download the trial and it lets you blacklist one app for free which is all you need most of the time so it works for now..

**Comment by BlueThunder93** [comment]
You can also get PokePatch from Cydia that patches the jailbreak detection for the game.

**Comment by Iomega0318** [comment]
Ahh good to know, I checked Flex 2 but there was nothing on there yet.. and honestly I'm not a fan of tsProtector haha..

**Comment by Lunat1k** [comment]
V42 Beta 1 works now on iOS9. no need to use the PokePatch. You can get the deb file on the main page.
